// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: asw.proto

package AswSvr

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFlowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineQRN string `protobuf:"bytes,1,opt,name=machineQRN,proto3" json:"machineQRN,omitempty"`
}

func (x *CreateFlowReq) Reset() {
	*x = CreateFlowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlowReq) ProtoMessage() {}

func (x *CreateFlowReq) ProtoReflect() protoreflect.Message {
	mi := &file_asw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlowReq.ProtoReflect.Descriptor instead.
func (*CreateFlowReq) Descriptor() ([]byte, []int) {
	return file_asw_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFlowReq) GetMachineQRN() string {
	if x != nil {
		return x.MachineQRN
	}
	return ""
}

type CreateFlowRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *CreateFlowRsp) Reset() {
	*x = CreateFlowRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlowRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlowRsp) ProtoMessage() {}

func (x *CreateFlowRsp) ProtoReflect() protoreflect.Message {
	mi := &file_asw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlowRsp.ProtoReflect.Descriptor instead.
func (*CreateFlowRsp) Descriptor() ([]byte, []int) {
	return file_asw_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFlowRsp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_asw_proto protoreflect.FileDescriptor

var file_asw_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x73, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x73, 0x77,
	0x2e, 0x41, 0x73, 0x77, 0x53, 0x76, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x51, 0x52, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x51, 0x52, 0x4e, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6c, 0x6f, 0x77, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x32, 0x69, 0x0a, 0x0b, 0x46,
	0x6c, 0x6f, 0x77, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x5a, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x19, 0x2e, 0x61, 0x73, 0x77, 0x2e, 0x41,
	0x73, 0x77, 0x53, 0x76, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x73, 0x77, 0x2e, 0x41, 0x73, 0x77, 0x53, 0x76, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x73, 0x70, 0x22, 0x16,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0b, 0x2f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x6f, 0x77, 0x3a, 0x01, 0x2a, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x62, 0x33, 0x2f, 0x61, 0x73,
	0x77, 0x2f, 0x41, 0x73, 0x77, 0x53, 0x76, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asw_proto_rawDescOnce sync.Once
	file_asw_proto_rawDescData = file_asw_proto_rawDesc
)

func file_asw_proto_rawDescGZIP() []byte {
	file_asw_proto_rawDescOnce.Do(func() {
		file_asw_proto_rawDescData = protoimpl.X.CompressGZIP(file_asw_proto_rawDescData)
	})
	return file_asw_proto_rawDescData
}

var file_asw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_asw_proto_goTypes = []interface{}{
	(*CreateFlowReq)(nil), // 0: asw.AswSvr.CreateFlowReq
	(*CreateFlowRsp)(nil), // 1: asw.AswSvr.CreateFlowRsp
}
var file_asw_proto_depIdxs = []int32{
	0, // 0: asw.AswSvr.FlowManager.CreateFlow:input_type -> asw.AswSvr.CreateFlowReq
	1, // 1: asw.AswSvr.FlowManager.CreateFlow:output_type -> asw.AswSvr.CreateFlowRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asw_proto_init() }
func file_asw_proto_init() {
	if File_asw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlowRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asw_proto_goTypes,
		DependencyIndexes: file_asw_proto_depIdxs,
		MessageInfos:      file_asw_proto_msgTypes,
	}.Build()
	File_asw_proto = out.File
	file_asw_proto_rawDesc = nil
	file_asw_proto_goTypes = nil
	file_asw_proto_depIdxs = nil
}
